version: 2

models:
  - name: dim_customers
    description: "Customer dimension table with geolocation enrichment. One row per customer_order_id."
    config:
      contract:
        enforced: true
    columns:
      - name: customer_order_id
        data_type: string
        description: "{{ doc('customer_order_id') }}"
        tests:
          - not_null
          - unique
      - name: customer_id
        data_type: string
        description: "{{ doc('customer_id_marts') }}"
        tests:
          - not_null
      - name: customer_zip_code
        data_type: string
        description: "{{ doc('customer_zip_code_prefix') }}"
      - name: customer_city
        data_type: string
        description: "{{ doc('customer_city') }}"
      - name: customer_state
        data_type: string
        description: "{{ doc('customer_state') }}"
      - name: customer_lat
        data_type: float
        description: "{{ doc('geolocation_lat') }}"
      - name: customer_lng
        data_type: float
        description: "{{ doc('geolocation_lng') }}"

  - name: dim_dates
    description: "Date dimension table with calendar attributes for analytics and reporting."
    config:
      contract:
        enforced: true
    columns:
      - name: date_day
        data_type: date
        description: "{{ doc('dim_dates_date') }}"
        tests:
          - not_null
          - unique
      - name: year
        data_type: integer
        description: "{{ doc('dim_dates_year') }}"
      - name: month
        data_type: integer
        description: "{{ doc('dim_dates_month') }}"
      - name: day
        data_type: integer
        description: "{{ doc('dim_dates_day') }}"
      - name: quarter
        data_type: integer
        description: "{{ doc('dim_dates_quarter') }}"
      - name: week
        data_type: integer
        description: "{{ doc('dim_dates_week') }}"
      - name: day_of_week
        data_type: integer
        description: "{{ doc('dim_dates_day_of_week') }}"
      - name: is_weekend
        data_type: boolean
        description: "{{ doc('dim_dates_is_weekend') }}"
      - name: is_month_start
        data_type: boolean
        description: "{{ doc('dim_dates_is_month_start') }}"
      - name: is_month_end
        data_type: boolean
        description: "{{ doc('dim_dates_is_month_end') }}"
      - name: day_abbr
        data_type: string
        description: "{{ doc('dim_dates_day_abbr') }}"
      - name: month_abbr
        data_type: string
        description: "{{ doc('dim_dates_month_abbr') }}"

  - name: dim_marketing
    description: "Marketing dimension table containing lead and closed deal attributes for analysis."
    config:
      contract:
        enforced: true
    columns:
      - name: mql_id
        data_type: string
        description: "{{ doc('mql_id') }}"
        tests:
          - not_null
          - unique
      - name: first_contact_date
        data_type: date
        description: "{{ doc('first_contact_date') }}"
      - name: landing_page_id
        data_type: string
        description: "{{ doc('landing_page_id') }}"
      - name: origin
        data_type: string
        description: "{{ doc('origin') }}"
      - name: channel
        data_type: string
        description: "{{ doc('channel') }}"
      - name: seller_id
        data_type: string
        description: "{{ doc('seller_id_fk') }}"
      - name: sdr_id
        data_type: string
        description: "{{ doc('sdr_id') }}"
      - name: sr_id
        data_type: string
        description: "{{ doc('sr_id') }}"
      - name: business_segment
        data_type: string
        description: "{{ doc('business_segment') }}"
      - name: lead_type
        data_type: string
        description: "{{ doc('lead_type') }}"
      - name: lead_behaviour_profile
        data_type: string
        description: "{{ doc('lead_behaviour_profile') }}"
      - name: has_company
        data_type: boolean
        description: "{{ doc('has_company') }}"
      - name: has_gtin
        data_type: boolean
        description: "{{ doc('has_gtin') }}"
      - name: average_stock
        data_type: string
        description: "{{ doc('average_stock') }}"
      - name: business_type
        data_type: string
        description: "{{ doc('business_type') }}"

  - name: dim_products
    description: "Product dimension table containing product attributes and categories."
    config:
      contract:
        enforced: true
    columns:
      - name: product_id
        data_type: string
        description: "{{ doc('product_id_pk') }}"
        tests:
          - not_null
          - unique
      - name: category
        data_type: string
        description: "{{ doc('category') }}"
      - name: subcategory
        data_type: string
        description: "{{ doc('subcategory') }}"
      - name: name_length
        data_type: integer
        description: "{{ doc('product_name_length') }}"
      - name: description_length
        data_type: integer
        description: "{{ doc('product_description_length') }}"
      - name: photos_qty
        data_type: integer
        description: "{{ doc('product_photos_qty') }}"
      - name: weight_g
        data_type: integer
        description: "{{ doc('product_weight_g') }}"
      - name: length_cm
        data_type: integer
        description: "{{ doc('product_length_cm') }}"
      - name: height_cm
        data_type: integer
        description: "{{ doc('product_height_cm') }}"
      - name: width_cm
        data_type: integer
        description: "{{ doc('product_width_cm') }}"

  - name: dim_sellers
    description: "Seller dimension table with geolocation enrichment. One row per seller."
    config:
      contract:
        enforced: true
    columns:
      - name: seller_id
        data_type: string
        description: "{{ doc('seller_id_pk') }}"
        tests:
          - not_null
          - unique
      - name: seller_zip_code
        data_type: string
        description: "{{ doc('seller_zip_code_prefix') }}"
      - name: seller_city
        data_type: string
        description: "{{ doc('seller_city') }}"
      - name: seller_state
        data_type: string
        description: "{{ doc('seller_state') }}"
      - name: seller_lat
        data_type: float
        description: "{{ doc('geolocation_lat') }}"
      - name: seller_lng
        data_type: float
        description: "{{ doc('geolocation_lng') }}"
